refactor: improve notifications and error handling
AntonVanAssche/music-controls.nvim pull request #2
Opened 2024-07-19 02:38 UTC by sjclayton

Hey,

I have cleaned things up a bit, and tried to improve the appearance of the notifications a bit... I've also added some error handling around the notifications.

Try calling `MusicPlay` now without Spotify or your `default_player` running... no more command output from `playerctl` corrupting the Neovim window if the player isn't running.

Take a look at things and let me know what you think! 😀

2024-07-19 14:56 UTC, AntonVanAssche requested changes

2024-07-19 14:56 UTC, AntonVanAssche commented on lua/music-controls/init.lua
> +-- Execute the 'playerctl' command and get it's output.
Correct me if I'm wrong, but shouldn't it be:

```suggestion
-- Execute the 'playerctl' command and get its output.
```

Since `it's` is short for `it is`.

2024-07-19 14:56 UTC, AntonVanAssche commented on lua/music-controls/init.lua
>      end
Please fix the indentation here.

```suggestion
    if output then
        for _, line in ipairs(output) do
            remove_newline(line)
            result = line
        end
    end
```

2024-07-19 15:18 UTC, sjclayton commented on lua/music-controls/init.lua
>      end
Done in my lastest commit.

2024-07-19 15:36 UTC, sjclayton commented on lua/music-controls/init.lua
> +-- Execute the 'playerctl' command and get it's output.
Good catch... sometimes they get by me.

2024-07-19 20:17 UTC, sjclayton commented
Everything should be good now, I'm not planning any more changes... Unless you find anything else for me, if so just call it out and I'll look at it.

Just had to catch that unreachable spot I missed earlier. Thanks again for the review! 💯

2024-07-20 12:09 UTC, AntonVanAssche approved these changes
Looks good to me! Thanks for your contribution.

2024-07-20 12:10 UTC, merged