fix: bug with shuffle not getting state before toggle
AntonVanAssche/music-controls.nvim pull request #4
Opened 2024-07-24 19:49 UTC by sjclayton

Caught a small bug, and figure I'd zap it straight away... ⚡

2024-07-25 10:25 UTC, AntonVanAssche requested changes

2024-07-25 10:25 UTC, AntonVanAssche commented on lua/music-controls/init.lua
> +    end
Please make sure to use 4 spaces as indentation.

```suggestion
    if current_status == 'Off' then
        exec_command('playerctl -p  '.. player[1] .. ' shuffle toggle on')
    else
        exec_command('playerctl -p  '.. player[1] .. ' shuffle toggle off')
    end
```

2024-07-25 10:49 UTC, sjclayton commented on lua/music-controls/init.lua
> +    end
I'm going to add a `.editorconfig` file so my auto format on save is proper for this project... I don't like having to pay attention to whether or not I've disabled it before I save.

Also, sometimes I'm not convinced tree-sitter's indent feature works correctly all the time.

2024-07-25 11:12 UTC, sjclayton commented
All good! _lol... shakes head_ 😆

2024-07-26 11:36 UTC, AntonVanAssche approved these changes
Looks great! Thanks for this fix.

2024-07-26 11:37 UTC, AntonVanAssche commented
> I looked at your Neovim config, and it appears you have Stylua installed through Mason but you have nothing that is actually calling it to do the formatting, so essentially it's doing nothing... you'd need something like either [none-ls.nvim](https://github.com/nvimtools/none-ls.nvim) or [conform.nvim](https://github.com/stevearc/conform.nvim) (which is excellent btw) to enable Stylua to run on save, or when called from a keymap for example.

Thanks for letting me know, I didn't know this. (I don't write Lua that often, besides config stuff 😉)

2024-07-26 11:37 UTC, merged

2024-07-26 12:16 UTC, sjclayton commented
> Thanks for letting me know, I didn't know this. (I don't write Lua that often, besides config stuff 😉)

Even if that's all you primarily write in Lua, you can copy that `.stylua.toml` into your config directory and then it'll make sure all your configs are formatted and kept in a consistent state... I do it with mine, helps if you occasionally format a function slightly wrong or miss commas in plugin specs etc.